### ISSUE TITLE
No Divider found in lower part

### ISSUE THREAD

**Issue by pramodshukla1011** [ankitjamuar/SwiftUI-COVID-19#1]

**Comment by ankitjamuar** [comment]
The divider were removed for the sake of easyness of the UI, can be added as an  vStack

**Comment by pramodshukla1011** [comment]
Ok then share the code pls for the same

**Comment by ankitjamuar** [comment]
It might take some time for me to do that as I am occupied with many parallel projects. The changes you are requesting is very small, you just need to add one VStack between those icons
